from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home_view,name='home'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.manage_profile, name='manage_profile'),
    # path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('add_student/',views.add_student,name='add_student'),
    path('manage_student/',views.manage_student,name='manage_student'),
    path('update_student/<int:id>/',views.update_student,name='update_student'),
    path('delete_student/<int:id>/',views.delete_student,name='delete_student'),
    path('add_teacher/',views.add_teacher,name='add_teacher'),
    path('manage_teacher/',views.manage_teacher,name='manage_teacher'),
    path('update_teacher/<int:id>/',views.update_teacher,name='update_teacher'),
    path('delete_teacher/<int:id>/',views.delete_teacher,name='delete_teacher'),
    path('add_department/',views.add_department,name='add_department'),
    path('manage_department/',views.manage_department,name='manage_department'),
    path('update_department/<int:id>/',views.update_department,name='update_department'),
    path('delete_department/<int:id>/',views.delete_department,name='delete_department'),
    path('add_campus/',views.add_campus,name='add_campus'),
    path('manage_campus/',views.manage_campus,name='manage_campus'),
    path('update_camps/<int:id>/',views.update_campus,name='update_campus'),
    path('delete_campus/<int:id>/',views.delete_campus,name='delete_campus'),
    path('add_club/',views.add_club,name='add_club'),
    path('manage_club/',views.manage_club,name='manage_club'),
    path('update_club/<int:id>/',views.update_club,name='update_club'),
    path('delete_club/<int:id>/',views.delete_club,name='delete_club'),
    path('add_parent/',views.add_parent,name='add_parent'),
    path('manage_parent/',views.manage_parent,name='manage_parent'),
    path('update_parent/<int:id>/',views.update_parent,name='update_parent'),
    path('delete_parent/<int:id>/',views.delete_parent,name='delete_parent'),
    path('add_library/',views.add_library,name='add_library'),
    path('manage_library/',views.manage_library,name='manage_library'),
    path('update_library/<int:id>/',views.update_library,name='update_library'),
    path('delete_library/<int:id>/',views.delete_library,name='delete_library'),
    path('add_routine/',views.add_routine,name='add_routine'),
    path('manage_routine/',views.manage_routine,name='manage_routine'),
    path('update_routine/<int:id>/',views.update_routine,name='update_routine'),
    path('delete_routine/<int:id>/',views.delete_routine,name='delete_routine'),
    path('add_event/',views.add_event,name='add_event'),
    path('manage_event/',views.manage_event,name='manage_event'),
    path('update_event/<int:id>/',views.update_event,name='update_event'),
    path('delete_event/<int:id>/',views.delete_Event,name='delete_event'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)